trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: "Instalar Node.js"

  - script: |
      cd backend
      npm install
      npm test
    displayName: "Probar backend"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "backend"
      ArtifactName: "backend"
      publishLocation: "Container"
