trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: "Instalar Node.js"

  - script: |
      cd frontend
      npm install
      npm run build
    displayName: "Compilar React"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "frontend/build"
      ArtifactName: "frontend"
      publishLocation: "Container"
